### ISSUE TITLE
Unable to clear trash when deleting dead symlink

### ISSUE THREAD

**Issue by omernaveedxyz** [oberblastmeister/trashy#97]
### Expected behavior

When a dead symlinked file is deleted, it should be able to be cleared from the trash directory

### Actual behavior

When a dead symlink is deleted, it correctly goes into the trash directory, but the trash restore/empty commands no longer work as long as the dead symlink is there

### Steps to reproduce behavior

```bash
touch test
ln -sf test test2

trash put test
trash empty

trash put test2
trash empty
```

The final command will result in following error
```bash
thread 'main' panicked at 'assertion failed: file.exists()', /build/trashy-2.0.0-vendor.tar.gz/trash/src/freedesktop.rs:238:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by santibreo** [comment]
The same was happening to me.

This issue is an issue with [trash](https://github.com/Byron/trash-rs), but it was corrected by [this commit](https://github.com/Byron/trash-rs/commit/919801376bc44fa3c4948349690c7e912be2dd3a#diff-4525023a63885765bb8b8a4f6ad87b116f2ee8494980d797a91820041ad1fb8eR239). So updating trash dependency version from 3.0.1 to 3.0.2 should solve the issue.

**Comment by perlinm** [comment]
> This issue is an issue with [trash](https://github.com/Byron/trash-rs), but it was corrected by [this commit](https://github.com/Byron/trash-rs/commit/919801376bc44fa3c4948349690c7e912be2dd3a#diff-4525023a63885765bb8b8a4f6ad87b116f2ee8494980d797a91820041ad1fb8eR239). So updating trash dependency version from 3.0.1 to 3.0.2 should solve the issue. At least I have tried, and it solved my case.

Completed by #101.  I think we can close this issue.

**Comment by j-lakeman** [comment]
Similar thing happened to me on trashy 2.0.0:

```
[I] ➜  ~ trash empty bash

3 items will be emptied
╭───┬──────────────┬───────────────────╮
│ i │ Time         │ Path              │
├───┼──────────────┼───────────────────┤
│ 2 │ 7 months ago │ /home/xxx/.bashrc │
│ 1 │ 7 months ago │ /home/xxx/.bashrc │
│ 0 │ 7 months ago │ /home/xxx/.bashrc │
╰───┴──────────────┴───────────────────╯
Are you sure? yes
thread 'main' panicked at 'assertion failed: file.exists()', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/trash-2.1.5/src/freedesktop.rs:238:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The three files are all dead symlinks.
Pls reopen

**Comment by santibreo** [comment]
The issue was solved by committing [this](https://github.com/oberblastmeister/trashy/pull/101/commits/1e033e5d985f73dfa77d28b3939ceacf22b1be30# ) but this change is not incorporated to version 2.0.0 (as you can see [here](https://github.com/oberblastmeister/trashy/blob/23a2568d9a3373fc5fb15baa81881eb0f76cfa22/Cargo.toml#L26)).

**Comment by j-lakeman** [comment]
Any idea when this will be incorporated in a new release?
